version: '3.1'

services:

  postgresql:
    image: postgres:12.12
    container_name: POSTGRES-PORTFOLIO
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - 5432:5432
    volumes:
      - C:\dados\volumes\databases\PORTFOLIO:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-portfolio
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgpassword
    ports:
      - 8080:80
volumes:
  my-db:
