version: '3.1'

services:

  postgresql:
    container_name: POSTGRES-PORTFOLIO
    image: postgres:12.12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    # restart: unless-stopped
    volumes:
      - C:\dados\volumes\databases\PORTFOLIO:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin-portfolio
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: dbpassword
    ports:
      - 8080:80
volumes:
  my-db: