version: '3.1'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: dbpassword
    ports:
      - 8080:80
volumes:
  my-db: